### ISSUE TITLE
Use of the replace string method.

### ISSUE THREAD

**Issue by kamdave** [henrytirla/Practical-Introduction-to-python#1]
Exercise 6 (qsn:5)
If you are to use a different String say ('common' instead of 'Qerbt') with str[1] occuring more than once. Then we are likely to have a problem of the asterisk in more than one place .
I think if we approach that problem with string slices and concatenation to create a new string then we would have no issues

**Comment by henrytirla** [comment]
Hey Thank you for your feedback .I Just merged your pull request
